# bin configuration
string bin_id
string ObjectName
string[] BinContents
int8 ObjectIndex  # will be removed
int8[] RemovedObjectIndices
# sensor information
sensor_msgs/Image xtion_rgb_image
sensor_msgs/CameraInfo xtion_rgb_info
sensor_msgs/Image xtion_depth_image
sensor_msgs/CameraInfo xtion_depth_info
sensor_msgs/Image pg_rgb_image
sensor_msgs/CameraInfo pg_rgb_info
bool use_cloud
sensor_msgs/PointCloud2 cloud
---
# object poses
bool found
Object[] items_in_bin
# not used in UTS setup
# apc_msgs/Rect object_rect
# geometry_msgs/Pose object_pose
# shape_msgs/SolidPrimitive object_shape
